### ISSUE TITLE
Remove/uninstall btc-rpc-explorer

### ISSUE THREAD

**Issue by Relaxo143** [Samourai-Wallet/samourai-dojo#135]
I recently upgraded my dojo to 1.4.1 and I didn't see the new explorer until later. Now I would like to uninstall that part of the bundle or at least prevent it from starting since it requires a lot of RAM. How could I do that? the install flag is set to off, but I guess I should have done that before upgrading.

**Comment by LaurentMT** [comment]
You just need to set the option `EXPLORER_INSTALL` to `off` in `docker-explorer.conf` and to restart your Dojo. It will deactivate the explorer.

You can confirm that it worked by running the command `docker ps` after the restart. You should see that the explorer container doesn't run.

**Comment by Relaxo143** [comment]
I get this with docker ps 
` 2 days ago          Up 46 minutes       8080-8082/tcp         nodejs
df4ee903f695        samouraiwallet/dojo-explorer:1.0.0   "/home/node/app/rest…" 
`
The flag is set to off. When I restart it it says stopping explorer and then starting explorer.. so it seems it's running.

**Comment by LaurentMT** [comment]
I don't have a Dojo 1.4.1 available right now but I've been able to deactivate the explorer on Dojo 1.5 with the following procedure (If I'm not mistaken, Dojo 1.4.1 should have the same behavior):
- Edit .../docker/my-dojo/conf/docker-explorer.conf and set `EXPLORER_INSTALL` to `off`
- Stop Dojo with the command `./dojo.sh stop` => all containers are stopped except the explorer
- Start Dojo with the command `./dojo.sh start` => the explorer container is removed, others containers are started. This command returns the following traces:
```
> ./dojo.sh start
Removing orphan container "explorer"
Starting db   ... done
Recreating tor   ... done
...
Recreating nginx   ... done
``` 
- Command `docker ps` doesn't display the explorer container anymore

**Comment by Relaxo143** [comment]
It worked, thanks
