### ISSUE TITLE
Mysql 5.7 docker image not supported on arm64 devices 

### ISSUE THREAD

**Issue by MrHash** [Samourai-Wallet/samourai-dojo#16]
I think this is a long standing issue at https://github.com/docker-library/mysql/issues/318

Consider swapping for an alternative build based on architecture switch or using mariadb or other compatible option.

more info: https://hub.docker.com/r/mysql/mysql-server/

**Comment by MrHash** [comment]
in my setup a straight swap of mysql:5.7 to mariadb:10.4 works seamlessly for armv8

**Comment by Technifocal** [comment]
I had to execute `mysql -h"db" -u"root" -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE" < /docker-entrypoint-initdb.d/1_db.sql` inside the `mariadb` container to get this working.

See #22.

**Comment by MrHash** [comment]
Hmm that's interesting, i didn't have that problem afaik but i'll feedback if i see it. It might be that the install failed first time for some reason and this had to be run to complete the install script.
