### ISSUE TITLE
Can I change the password on the explorer service?

### ISSUE THREAD

**Issue by dmp1ce** [Samourai-Wallet/samourai-dojo#170]
**Describe the issue**
I want to change the password on my explorer service. It has already been built but I don't like the password.

**Desktop (please complete the following information):**
 - OS: Docker on Ubuntu
 - Dojo Version is 1.8.0
 - I'm using external bitcoind and have enable the bitcoin explorer service on the dojo

**Additional context**
I have change the password in the `docker-explorer.conf.tpl` file but I think the password needs to change in the `docker-explorer.conf.save` file. Will it work if I change the password in the `docker-explorer.conf.save` file and rebuild the docker images?

**Comment by LaurentMT** [comment]
You can change this password by modifying the value of EXPLORER_KEY in docker-explorer.conf

Notes:
- docker-explorer.conf.save is a backup of docker-explorer.conf created during the upgrade of your Dojo,
- docker-explorer.conf.tpl is a template for docker-explorer.conf that is released with each new version.
- this repository is now inactive. The new active repository (code, pull requests, issues, etc) is https://code.samourai.io/dojo/samourai-dojo

**Comment by dmp1ce** [comment]
Thanks! Very informative and helpful. I ran `./dojo.sh upgrade` to rebuild the container after modifying `docker-explorer.conf`.

I couldn't create an account on code.samourai.io for some reason. I already created a support ticket for that issue.
