### ISSUE TITLE
Please add documentation about how to use a pre-existing bitcoind installation

### ISSUE THREAD

**Issue by qbert911** [Samourai-Wallet/samourai-dojo#2]
I very much appreciate the beginner friendly setup method.
I suspect there are quite a number of intermediate users who already run a full node and would like to add dojo on top of it without fouling up their current bitcoin demon.

The install script may be able to handle this already  (I am wary to test it on my lightning node server without knowing what will happen).
If that is the case then please just update the documentation to explain what will happen if you run the setup script on a Linux machine already running bitcoind.

Great Work!

**Comment by kenshin-samourai** [comment]
The setup script provided by MyDojo (dockerized version of Dojo) installs and runs a new instance of bitcoind in a docker container. This script doesn't provide an option allowing to bypass this install and to plug Dojo on an external bitcoind.

If you use the setup script on a machine already running a bitcoind, your machine will host 2 full nodes. The full node installed by MyDojo will run as a Tor hidden service.
