### ISSUE TITLE
Docker compose script fails to setup database tables/schemas

### ISSUE THREAD

**Issue by Technifocal** [Samourai-Wallet/samourai-dojo#22]
After a lot of failures (:cry:) I've concluded that the docker-compose script does not actually setup a operational Dojo stack.

[1_db.sql.tpl](https://github.com/Samourai-Wallet/samourai-dojo/blob/e3d515f7096f5b5350bdcc69ad1cf1f5afa5dfee/db-scripts/1_db.sql.tpl) gets copied to `1_db.sql` [here](https://github.com/Samourai-Wallet/samourai-dojo/blob/e3d515f7096f5b5350bdcc69ad1cf1f5afa5dfee/docker/my-dojo/install/install-scripts.sh#L18) and then is never used again. This means that the database is at no point initialized and thus the entity of Dojo doesn't work (Oops, guess I'm the first non-dev user! :eyes:).

I assume [this](https://github.com/Samourai-Wallet/samourai-dojo/blob/02e629e1a61b910d3d857cfd4cfbd4f418d236c2/docker/my-dojo/mysql/update-db.sh#L11-L14) code should also contain another block above that is roughly:

```
if [ -f /docker-entrypoint-initdb.d/1_db.sql ]; then
  mysql -h"db" -u"root" -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE" < /docker-entrypoint-initdb.d/1_db.sql
  echo "Updated database with 1_db.sql"
fi
```

**Comment by kenshin-samourai** [comment]
database initialization during **first install of dojo** is a 3 steps process:
1/ 1_db.sql.tpl gets copied to 1_db.sql ([here](https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/docker/my-dojo/install/install-scripts.sh#L18))
2/ 1_db.sql gets copied into the /docker-entrypoint-initdb.d directory of the mysql container  ([here](https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/docker/my-dojo/mysql/Dockerfile#L13))
3/ 1_db.sql is executed ([here](https://github.com/docker-library/mysql/blob/26380f33a0fcd07dda35e37516eb24eaf962845c/5.7/docker-entrypoint.sh#L196))

the last step is a feature provided by the mysql docker image (see section "Initializing a fresh instance" of this [page](https://hub.docker.com/_/mysql))

this process has been tested by non-dev users. it's likely that your "failures" have another cause.

**Comment by Technifocal** [comment]
I'm beyond stupid. I completely forgot I swapped `mysql` to `mariadb`. Sorry for wasting your time.

**Comment by kenshin-samourai** [comment]
no problem
