### ISSUE TITLE
Using a blockchain datadir at the host machine mounted at bitcoind docker

### ISSUE THREAD

**Issue by pxsocs** [Samourai-Wallet/samourai-dojo#26]
Wondering if there's a way to mount a fully synched blockchain folder at the host machine to the Dojo bitcoind docker image. 

This would avoid having to download a duplicate blockchain and potentially save time for users that already have a full node running at the host machine.

**Comment by LaurentMT** [comment]
Version 1.1 will provide an option allowing to skip the installation of a new full node. When this option is activated, Dojo will use an external bitcoind running on the host machine.

See this [doc](https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/doc/DOCKER_advanced_setups.md) for the details.

**Comment by pxsocs** [comment]
When I tried to run `./dojo.sh install` after including `BITCOIND_INSTALL=off` at the config file, it still tried to install bitcoind and seemed to ignore this flag.

**Comment by LaurentMT** [comment]
Did you use the source code which is currently in the "develop" branch  for this test?

It was your first installation of Dojo on this machine?

**Comment by pxsocs** [comment]
Ha! No, used the original source code. Will retry with the develop one and report back.

**Comment by LaurentMT** [comment]
Ok! An important point. Dojo v1.1 will have a new command for upgrading an already installed Dojo: ./dojo.sh upgrade. See this [doc](https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/doc/DOCKER_setup.md).

**Comment by pxsocs** [comment]
Worked! Officially __RUNNING DOJO__ :)
