### ISSUE TITLE
Error: Content Security Policy: The page’s settings blocked the loading of a resource

### ISSUE THREAD

**Issue by pxsocs** [Samourai-Wallet/samourai-dojo#29]
I'm getting the following error message while trying to login.

__Please note that this happens only in one of the 3 different TOR browsers I've used__. 

But on this specific machine, I cannot login to the onion address and admin page. I've tried reinstalling the browser but the error persists. 

When checking the browser console there are several error messages like the below:
```
Content Security Policy: The page’s settings blocked the loading of a resource at http://[address].onion/admin/index.js (“script-src”).
```

**Comment by LaurentMT** [comment]
My best guess is that you have NoScript activated on this Tor browser.

You need to mark the onion url of your Dojo as trusted:
- click on the NoScript icon,
- click on the "TRUSTED" icon ("S" icon),
- click on the page to reload its content.

![tor_noscriptpng](https://user-images.githubusercontent.com/5204318/60656604-05990f00-9e50-11e9-8c0b-45ed46acc98a.png)

**Comment by pxsocs** [comment]
NoScript was the issue. Fixed. Thanks.
