### ISSUE TITLE
Expose bitcoind RPC API to the host machine

### ISSUE THREAD

**Issue by LaurentMT** [Samourai-Wallet/samourai-dojo#3]
It seems that some users are willing to use the bitcoind packaged in docker as a source for external apps running on the docker host (e.g;: LN node, etc).

May be we could expose the port of the RPC API to the localhost, with something like

```
bitcoind:
  ports:
    - "127.0.0.1:28256:28256"
```

**Comment by kenshin-samourai** [comment]
a couple of remarks
- localhost isn't going to work when containers run in a vm (mac os, windows)
- make it optional? (default = no port exposed)

**Comment by LaurentMT** [comment]
It might be a good idea to expose all ZMQ ports when this option is activated.
Some apps rely on notifications which aren't required by Dojo.
(e.g.: lnd requires zmqpubrawblock  source: https://gist.github.com/05nelsonm/ef55dcc1fb3aa588c8135cd107ee5d8c)

**Comment by kenshin-samourai** [comment]
support of additional ports and number of rpc threads implemented in PR #12
