### ISSUE TITLE
Appropriate steps for getting XPUB

### ISSUE THREAD

**Issue by pxsocs** [Samourai-Wallet/samourai-dojo#30]
I'm following the steps below but not being able to get XPUB information resulting in an error:
`Cannot GET /xpub/xpub123456[...]`

Steps taken:

1. Get authentication token from a POST request to:
url: `http://[my_onion_address]/v2/auth/login`
post_fields: `{"apikey": [my_API_key]}`
_Result_: __Success__ with Json:
{'authorizations': {'access_token': 'my_token', 'refresh_token': 'my_token'}}

2. Use the access_token to send a POST request to add HD address:
url: `http://[my_onion_address]/v2/xpub`
post_fields: `{"xpub": [my_xpub], "type": "new", "at": [my_at]}`
_Result_: __Success__ with Json:
{"status": "ok"}

3. Send a GET request to receive details of HD address:
url: `http://[my_onion_address]/v2/xpub/[my_xpub]/info?at=[my_at]`
_Result_: __Fails__ - receive message back:
`Cannot GET /xpub/xpub123456[...]/info`

__Note:__ 
By changing the GET url to: 
`http://[my_onion_address]/v2/support/xpub/[my_xpub]/info?at=[my_at]`

An error json is returned:
```
{
  "status": "error",
  "error": "Your current access rights do not allow this operation"
}
```

I would believe I'm probably using the wrong url path for the GET request.

**Comment by Technifocal** [comment]
Don't query `/info`, just simply:

`torify curl --silent "http://${URL}/v2/xpub/zpubREDACTED?at=${AUTH}"`

Returns:

```
{
  "status": "ok",
  "data": {
    "balance": redacted,
    "unused": {
      "external": redacted,
      "internal": redacted
    },
    "derivation": "BIP84",
    "created": redacted
  }
}
```

**Comment by pxsocs** [comment]
Changing the URL solved the issue. Thanks.
