### ISSUE TITLE
Change condition determining the Tracker mode?

### ISSUE THREAD

**Issue by LaurentMT** [Samourai-Wallet/samourai-dojo#31]
On startup, the tracker determines its catchup mode by [checking the height of the tip on the full node](https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/tracker/blockchain-processor.js#L62).

This condition doesn't seem adequate for the users who run Dojo on top of an external bitcoind which is already synchronized (=> the tracker switches in "normal" mode and download all the blocks since block 1).

Now that Dojo allows the use of an external bitcoind, it might be better to check the height of the tip in the database in order to determine the catchup mode.

**Comment by Technifocal** [comment]
Seems like the change was merged, should this issue be closed?
