### ISSUE TITLE
Shutdown of Dojo and bitcoind

### ISSUE THREAD

**Issue by LaurentMT** [Samourai-Wallet/samourai-dojo#35]
When Dojo is stopped with "dojo.sh stop", we have a delay of 15s between the shutdown of bitcoind and the shutdown of all docker containers.

The sweet spot for the duration of the delay seems to depend on multiple factors (hardware, operations processed by bitcoind before the shutdown, etc).

If the delay is too short, bitcoind will rewind the chain on next startup (takes a lot of time). On the other hand, a long static delay doesn't seem like a good tradeoff in term of UX.

It might be a good idea to replace the static delay by a loop testing if bitcoind is still up.

**Comment by Technifocal** [comment]
Here is an example (untested) loop demonstration what @LaurentMT mentioned at the end:

```
# Stop
stop() {
  if [ "$BITCOIND_INSTALL" == "on" ]; then
    if [ "$BITCOIND_EPHEMERAL_HS" = "on" ]; then
      docker exec -it tor rm -rf /var/lib/tor/hsv2bitcoind
    fi

    docker exec -it bitcoind bitcoin-cli \
      -rpcconnect=bitcoind \
      --rpcport=28256 \
      --rpcuser="$BITCOIND_RPC_USER" \
      --rpcpassword="$BITCOIND_RPC_PASSWORD" \
      stop

    echo "Preparing shutdown of dojo. Please wait."

    terminationCount=180;

    while [ "${?}" -eq "0" ] || [ "${terminationCount}" -le "0" ]; do
	    terminationCount="$((terminationCount - 1))";
	    sleep 1s;
    	docker exec -it bitcoind bitcoin-cli \
	      -rpcconnect=bitcoind \
	      --rpcport=28256 \
	      --rpcuser="$BITCOIND_RPC_USER" \
	      --rpcpassword="$BITCOIND_RPC_PASSWORD" \
	      uptime;
    done;
  fi

  yamlFiles=$(select_yaml_files)
  eval "docker-compose $yamlFiles down"
}
```

Potentially replace:

```
docker exec -it bitcoind bitcoin-cli \
	      -rpcconnect=bitcoind \
	      --rpcport=28256 \
	      --rpcuser="$BITCOIND_RPC_USER" \
	      --rpcpassword="$BITCOIND_RPC_PASSWORD" \
	      uptime;
```

with:

```
docker exec -it bitcoind true
```

Which will always return `true` while the bitcoin-cli container exists, or replace it with something that actually checks the container status.

**Comment by Technifocal** [comment]
Apparently Docker supports `wait`:

https://docs.docker.com/engine/reference/commandline/wait/

Replace the entire above loop with just:

`timeout 3m docker wait bitcoind`

It'll wait till the container closes, or 3 minutes. Whichever is sooner.
