### ISSUE TITLE
Tor Logs

### ISSUE THREAD

**Issue by 05nelsonm** [Samourai-Wallet/samourai-dojo#4]
Wondering if these are problems by any chance...

`./dojo.sh logs tor` output:

> tor         | Jun 09 22:48:54.836 [warn] CookieAuthFileGroupReadable is set, but will have no effect: you must specify an explicit CookieAuthFile to have it group-readable.

Adding `debug=tor` to bitcoin.conf, so `./dojo.sh logs bitcoind` output:

> 2019-06-09T23:21:58Z tor: Error connecting to Tor control socket
> 2019-06-09T23:21:58Z tor: Not connected to Tor control port 127.0.0.1:9051, trying to reconnect

**Comment by kenshin-samourai** [comment]
First log should be fixed by PR #7 

Second log is created by the TorController of bitcoind which is activated when listen=1.
This log will appear with PR #7 but it can be safely ignored.
