### ISSUE TITLE
Testnet config

### ISSUE THREAD

**Issue by waterdrop01** [Samourai-Wallet/samourai-dojo#52]
Hello,

is it possible to have two samourai-dojo running on the same machine, but different bitcoin chain?

- one for Bitcoin **mainnet**
- another one for Bitcoin **testnet**

Thank you!

**Comment by kenshin-samourai** [comment]
it isn't possible. see section "support of testnet" in this [doc](https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/doc/DOCKER_advanced_setups.md)

**Comment by waterdrop01** [comment]
Ok, got it. Farily easy!

Could you explain why running both mainnet and testnet on the same machine isn't possible?

Thanks!

**Comment by kenshin-samourai** [comment]
main reason is that current packaging doesn't support it but it doesn't seem a good idea to run test and prod infras in the same environment. 

better option: install the 2 dojo in 2 virtual machines running on the same machine.
