### ISSUE TITLE
API always responds {"status":"ok"}

### ISSUE THREAD

**Issue by waterdrop01** [Samourai-Wallet/samourai-dojo#57]
Hello,

my Bitcoind is still syncing. Still, I'm trying to hit the API (exposed by Nginx on port 80 right) but it always responds ```{"status":"ok"}```, and whatever is the URL I curl.

ex: ```curl -X GET https://myserver/autezdzd```  --->  ```{"status":"ok"}```

Also, Nginx and Nodejs docker images doesn't log anything. 

Any idea?

Thanks a lot :)

**Comment by LaurentMT** [comment]
Hi waterdrop0

This json is the response returned by the server if you request an unknown url.

Logs of nodejs are splitted between the different modules (API, Tracker, PushTx, Orchestrator).
You can display the logs of a specific module with the following dojo command
```
dojo.sh logs <module_name>
```

See the [docof dojo.sh](https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/doc/DOCKER_setup.md#shell_script)  for the detailed syntax or display this doc with the dojo command
```
dojo.sh help
```
