### ISSUE TITLE
2nd option (Full install using Docker for MacOS) - Is not working on Mac

### ISSUE THREAD

**Issue by ravi4chahal** [Samourai-Wallet/samourai-dojo#64]
I followed all steps in option 2 - (Full install using Docker for MacOS). 
1. Docer installed
2. tor is installed
3. Dojo copied on the relevant path.

Stuck at step ./dojo.sh install
It is giving me error "Line 7, too many arguments". It seems this .sh script is not supported.
Any idea whats going on. Did sombebody test it yet?

**Comment by LaurentMT** [comment]
May you provide a few details about your setup:
- OS version,
- Dojo version downloaded,
- full path of your <dojo_dir>.

**Comment by ravi4chahal** [comment]
> May you provide a few details about your setup:
> 
> * OS version,
> * Dojo version downloaded,
> * full path of your <dojo_dir>.
Here it is:

OS version: macOS Mojave 10.14.5
 Dojo version downloaded: latest samourai-dojo-master from this link https://github.com/Samourai-Wallet/samourai-dojo/archive/master.zip
full path: /Volumes/Apple 750 HD/users/dojou/dojo_dir

**Comment by LaurentMT** [comment]
May you try this:
- move your <dojo_dir> under a path that doesn't have space characters (e.g.: replace "Apple 750 HD" by "Apple_750_HD")
- restart the install of dojo (./dojo.sh install)

**Comment by ravi4chahal** [comment]
> May you try this:
> 
> * move your <dojo_dir> under a path that doesn't have space characters (e.g.: replace "Apple 750 HD" by "Apple_750_HD")
> * restart the install of dojo (./dojo.sh install)

yes!. this seems to fix the issue. Install started. thank you.
