### ISSUE TITLE
Bitcoind RPC API is still unreachable

### ISSUE THREAD

**Issue by ravi4chahal** [Samourai-Wallet/samourai-dojo#65]
I had successfully installed dojo on macOS Mojave using docker.
Blockchain also started downloading.. but somewhere in between , system restarted on its own.

Now I am getting this is tracker logs:
Bitcoind RPC API is still unreachable ... and it keeps waiting for the blocks.
Any issue with tor? I am not sure whats going on. Any help is appreceated

**Comment by LaurentMT** [comment]
Closed for inactivity
