### ISSUE TITLE
connect joinmarket  with bitcoind docker image from the dojo. 

### ISSUE THREAD

**Issue by stachrom** [Samourai-Wallet/samourai-dojo#69]
Is there a way,  that the joinmarket project (https://github.com/JoinMarket-Org/joinmarket-clientserver) can use the  bitcoin fullnode from  the  dojo? 

May be the wallet is missing ? 

dojo.sh bitcoin-cli getwalletinfo 
error code -32601
error message:
Method not Found

This means the wallet "function" is disabled. 
Would the dojo run with a activated fullnode wallet-function? 

Or is it not recomended?

**Comment by LaurentMT** [comment]
Indeed, the bitcoind wallet is deactivated in Dojo as it isn't used by Samourai Wallet.

The main risk is the user misconfiguriing its Dojo by exposing the RPC API to a public IP address (parameter BITCOIND_RPC_EXTERNAL_IP in docker-bitcoind.conf). As RPC communications are made in clear, that would expose the RPC password in clear and put the funds of the bitcoin wallet at risk.

Dojo may propose an additional option allowing to activate the bitcoind wallet when bitcoind is exposed to external apps but, to be honest, I'm not sure that it's a very good idea to make this option easier, especially for the less tech-savvy users. But it's just my opinion.

**Comment by LaurentMT** [comment]
Closed for inactivity
