### ISSUE TITLE
Suggestion: Use latest bitcoinjs-lib

### ISSUE THREAD

**Issue by junderw** [Samourai-Wallet/samourai-dojo#70]
Hello, I am the current maintainer of BitcoinJS.

Looking through your source, a quick find and replace of `bitcoin.HDNode` with `bitcoin.bip32` should work with the latest version of BitcoinJS Lib.

Also, address generation is much easier with our payments API.

v6 might remove the old address methods since they are redundant at this point.

We also have Psbt support now, so you might be able to encorporate it into some sort of offline signing feature etc. (Though that would probably be client-side and not dojo)

Please let me know if your devs have any questions, you can find me on keybase in the public team `bitcoinjslib`

**Comment by kenshin-samourai** [comment]
hey @junderw
indeed, upgrading bitcoinjs is on the roadmap.
thanks for the pull request. much appreciated.
