### ISSUE TITLE
Dojo stops communicating with bitcoind after some time

### ISSUE THREAD

**Issue by Relaxo143** [Samourai-Wallet/samourai-dojo#77]
Sometimes after a day, sometimes after a week of usage, Samourai Wallet can't fetch UTXOs. I check on Dojo and the tracker logs say "Bitcoind rpc unreachable. Retrying in 20 seconds." In fact Bitcoind is running and the rpc is working because other apps (LND, cgminer) are using it no problem. Restarting BItcoind solves the issue. Dojo thinks bitcoind is not ready to use when in fact it is. Side note: There should be a clear indication inside SW which shows if there is connection to Dojo or not. edit: I use Dojo with external bitcoind, running on windows 10.

**Comment by kenshin-samourai** [comment]
can you check in the logs of the tracker/api if you see some traces of network errors?
- dojo.sh logs tracker -d error -n 500
- dojo.sh logs api -d error -n 500

**Comment by Relaxo143** [comment]
[Tracker](https://pastebin.com/FE53Vpm8) and [api](https://pastebin.com/wiax3NXA) logs

**Comment by LaurentMT** [comment]
Closed for inactivty
