### ISSUE TITLE
install tor from archive of source files 

### ISSUE THREAD

**Issue by kenshin-samourai** [Samourai-Wallet/samourai-dojo#78]
A most welcome addition, however, there's one problem. Tor is still being built by cloing the git repo at torproject.com. If access to torproject.com is blocked, this doesn't work. Alternative would be to download the source from a website clone. For example: https://www.theonionrouter.com/tor-0.3.5.8.tar.gz

If the script were changed to pull the source tar instead of cloning from git a potential blocked user could edit the dockerfile and enter a clone he has access to.

_Originally posted by @burcakbaskan in https://github.com/Samourai-Wallet/samourai-dojo/pull/74#issuecomment-531870333_

**Comment by burcakbaskan** [comment]
I did this as a quick hack (so no signature checking and also to see if a newer version of tor broke anything and basically to try it on a raspberry pi 4). It's working

Changed bits here: (Sorry I don't know how to github)

ENV     TOR_HOME            /var/lib/tor
#ENV     TOR_URL             https://git.torproject.org/tor.git
ENV     TOR_SOURCE_URL      https://www.theonionrouter.com/tor-0.4.1.5.tar.gz
#ENV     TOR_VERSION         0.3.5.8
ENV     TOR_VERSION         0.4.1.5
ENV     GOLANG_DL_URL       https://dl.google.com/go
ENV     GOLANG_ARCHIVE      go1.13.linux-arm64.tar.gz
ENV     GOLANG_SHA256       e2a61328101eff3b9c1ba47ecfec5eb2fdc3eb35d8c27d505737ba98bfcb197b
ENV     OBFS4_URL           https://github.com/Yawning/obfs4.git
ENV     OBFS4_VERSION       0.0.11


# Install Tor
RUN     set -ex && \
        apt-get update && \
        apt-get install -y git libevent-dev zlib1g-dev libssl-dev gcc make automake ca-certificates autoconf musl-dev coreutils wget && \
        mkdir -p /usr/local/src/ && \
#        git clone "$TOR_URL" /usr/local/src/tor && \
#        cd /usr/local/src/tor && \
#        git checkout "tor-$TOR_VERSION" && \
        wget "$TOR_SOURCE_URL" && \
        tar -xvzf "tor-$TOR_VERSION.tar.gz" -C /usr/local/src && \
        cd "/usr/local/src/tor-$TOR_VERSION" && \
#        ./autogen.sh && \
        ./configure \
            --disable-asciidoc \
            --sysconfdir=/etc \
            --disable-unittests && \
        make && make install && \
        cd .. && \
        rm -rf tor

**Comment by k3tan172** [comment]
This issue has now come to fruition. https://git.torproject.org/tor.git is down and as such ```./dojo.sh install``` no longer works. Could a new release of ```https://github.com/Samourai-Wallet/samourai-dojo/archive/master.zip``` please be made to reflect this change?

**Comment by LaurentMT** [comment]
> Could a new release of `https://github.com/Samourai-Wallet/samourai-dojo/archive/master.zip` please be made to reflect this change?

PR #84 solves this. It's currently in the develop branch but it will be available in the next version of Dojo (1.3).
