### ISSUE TITLE
Dojo with existing full node

### ISSUE THREAD

**Issue by MrPaz** [Samourai-Wallet/samourai-dojo#88]
**Describe the issue**
A clear and concise description of what the issue is.

Maybe there's already Docs on this and I'm blind, but...  I already have a full node on my laptop.  How can I install of Dojo and use my existing full node/blockchain rather than a new Bitcoin install and IBD inside docker??  I'm not too familiar with Docker, except that I used it to set up BTCPayServer.

**Screenshots**
Do not submit screenshots containing PII (logins, passwords, keys, IP addresses, etc)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu vX.X] -- currently on Windows 10 with Ubuntu subsytem available, and hoping to use this laptop.  Alternatively I have another Ubuntu laptop, but, again, that laptop already has a full node on it that I'd prefer to use instead of resync'ing again
 - Dojo Version [e.g. 22]
 - Dojo Advanced Setups used (external bitcoind, bitcoind exposed to external apps, etc) -- this is what I'm looking for--Dojo with external bitcoind

**Additional context**
I'm on Windows 10 (with Docker), but have the Ubuntu subsystem available.  Not sure how much that will complicate things.

**Comment by LaurentMT** [comment]
My advice would be to follow the [setup doc](https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/doc/DOCKER_setup.md).

When you reach the step "Dojo provides a few additional settings for advanced setups", follow the instructions given in the "External Bitcoin full node" section of the [Advanced Setups doc](https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/doc/DOCKER_advanced_setups.md#external_bitcoind). Skip the last part ("Fast import of block headers in Dojo").

Then come back to the first doc and complete the last steps of the install procedure.

From my observations, the main issues met by users when trying to connect their Dojo to an external full node are:
- networking issues (a firewall blocks some ports, preventing the communcation between Dojo and the external full node)
- misconfiguration of bitcoind (rpcallowip doesn't allow connections from the NodeJs container, rpcbind doesn't expose the RPC API to a port accessible from the NodeJs container, etc)
- misconfiguration of the external bitcoind in Dojo (parameters set in docker-bitcoind.conf.tpl).

**Comment by LaurentMT** [comment]
Closed for inactivity
